FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o app ./cmd/app/main.go

FROM alpine:latest AS runner
WORKDIR /root/
#RUN apk --no-cache

COPY --from=builder /app/app .
COPY --from=builder /app/config ./config

#EXPOSE 8080

CMD ["./app"]
