// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/levinOo/geo-incedent-service/internal/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IncidentRepo is an autogenerated mock type for the IncidentRepo type
type IncidentRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, i
func (_m *IncidentRepo) Create(ctx context.Context, i *entity.Incident) error {
	ret := _m.Called(ctx, i)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Incident) error); ok {
		r0 = rf(ctx, i)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *IncidentRepo) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, limit, offset
func (_m *IncidentRepo) FindAll(ctx context.Context, limit string, offset string) ([]entity.Incident, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.Incident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]entity.Incident, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []entity.Incident); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Incident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *IncidentRepo) FindByID(ctx context.Context, id uuid.UUID) (*entity.Incident, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Incident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Incident, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Incident); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Incident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStats provides a mock function with given fields: ctx, minutes
func (_m *IncidentRepo) GetStats(ctx context.Context, minutes int) ([]*entity.IncidentStats, error) {
	ret := _m.Called(ctx, minutes)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 []*entity.IncidentStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*entity.IncidentStats, error)); ok {
		return rf(ctx, minutes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*entity.IncidentStats); ok {
		r0 = rf(ctx, minutes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.IncidentStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, minutes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Ping provides a mock function with given fields: ctx
func (_m *IncidentRepo) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, i
func (_m *IncidentRepo) Update(ctx context.Context, i *entity.Incident) error {
	ret := _m.Called(ctx, i)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Incident) error); ok {
		r0 = rf(ctx, i)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIncidentRepo creates a new instance of IncidentRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIncidentRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *IncidentRepo {
	mock := &IncidentRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
